[build-utils] Revert "Support empty directory entries for `glob()` and `download()`" (#9157)
Reverts vercel/vercel#9103

We believe the original PR is the cause of errors like:

> Error: EISDIR: illegal operation on a directory, read